export const GET_API_TODOLIST_BT = "GET_API_TODOLIST_BT";
export const ADD_API_TODOLIST_BT = "ADD_API_TODOLIST_BT";
export const DEL_API_TODOLIST_BT = "DEL_API_TODOLIST_BT";
export const CHECK_API_TODOLIST_BT = "CHECK_API_TODOLIST_BT";
export const REJECT_API_TODOLIST_BT = "REJECT_API_TODOLIST_BT";